### ISSUE TITLE
Make ask posts more readable

### ISSUE THREAD

**Issue by Firenz** [soulchainer/affray-devlog#10]
I think the best way could be to encapsulate the answer in a box like in caption. In this box, the user/anom icon should appear in a rounded fashion manner, then, the name in a bold letter. The question should be in a new line, so it can be read easily.

The answer should be outside the box, like a text post.

**Comment by soulchainer** [comment]
Solved by https://github.com/soulchainer/affray-devlog/commit/2e441f64f6bd668b7eda76f583198327d005b673
